#!/usr/bin/env bash

get_dns_info() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        dig_output=$(dig $sub.$domain | awk '/^;; ANSWER SECTION:$/,/^$/' | awk '/^.*\s+IN\s+A\s+.*$/')
        if [ -n "$dig_output" ]; then
            record_type=$(echo "$dig_output" | awk '{print $4}')
            destination=$(echo "$dig_output" | awk '{print $5}')
            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

get_dns_info "$1" "$2"

