#!/usr/bin/env bash
# rewriting task#1 with new rules
pkill apache2
chown nginx /etc/nginx/nginx.conf
chown u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
